# Generated by Django 3.2.12 on 2022-02-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1993-02-21'),
            preserve_default=False,
        ),
    ]
